version: '3.8'

services:
  python-server:
    container_name: python-server
    build:
      context: ./backend
    ports:
      - "8000:8000"
      - "3306:3306"
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./frontend
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
    - python-server
