apiVersion: apps/v1
kind: Deployment
metadata:
  name: openresty-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openresty
  template:
    metadata:
      labels:
        app: openresty
    spec:
      containers:
      - name: openresty
        image: 463865334882.dkr.ecr.eu-central-1.amazonaws.com/commit-fargate-openresty:latest
        ports:
        - containerPort: 80
        - containerPort: 443



---

apiVersion: v1
kind: Service
metadata:
  name: openresty-service
spec:
  selector:
    app: openresty
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
