version: 0.2

phases:
  post_build:
    commands:
      - echo Writing image definitions file...
      - printf '[{"name":"commit_fargate_python","imageUri":"463865334882.dkr.ecr.eu-central-1.amazonaws.com/commit_fargate_python:latest"}]' > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
